/**
 * Deploy and verify FxrpLzBridgeShim.
 *
 * Contract wraps the FXRP OFT Adapter so Flare smart-account memo-field
 * instructions can trigger a cross-chain bridge within the XRPL 1024-byte
 * per-memo limit. Per-route params are baked in at deploy time.
 *
 * Usage: yarn hardhat run scripts/layerZero/deployFxrpLzBridgeShim.ts --network coston2
 */

import hre, { run } from "hardhat";
import fs from "fs";
import path from "path";
import { EndpointId } from "@layerzerolabs/lz-definitions";
import { getFXRPTokenAddress } from "../utils/fassets";

const FxrpLzBridgeShim = artifacts.require("FxrpLzBridgeShim");

// Coston2 → Sepolia (FTestXRP) route.
const OFT_ADAPTER_ADDRESS = "0xCd3d2127935Ae82Af54Fc31cCD9D3440dbF46639";
const DST_EID = EndpointId.SEPOLIA_V2_TESTNET;
const EXECUTOR_GAS = 200_000;

async function deployAndVerify() {
    const fxrpAddress = await getFXRPTokenAddress();
    const constructorArgs: [string, string, number, number] = [fxrpAddress, OFT_ADAPTER_ADDRESS, DST_EID, EXECUTOR_GAS];

    const shim = await FxrpLzBridgeShim.new(...constructorArgs);
    console.log(`(${hre.network.name}) FxrpLzBridgeShim deployed to`, shim.address);
    console.log(`  fxrp        = ${fxrpAddress}`);
    console.log(`  oftAdapter  = ${OFT_ADAPTER_ADDRESS}`);
    console.log(`  dstEid      = ${DST_EID}`);
    console.log(`  executorGas = ${EXECUTOR_GAS}`);

    try {
        await run("verify:verify", {
            address: shim.address,
            constructorArguments: constructorArgs,
        });
        console.log("FxrpLzBridgeShim verified on block explorer.");
    } catch (e: unknown) {
        console.log("FxrpLzBridgeShim verification failed:", e instanceof Error ? e.message : e);
    }

    const deployFileContent =
        `// Generated by scripts/layerZero/deployFxrpLzBridgeShim.ts\n` +
        `export const fxrpAddress = "${fxrpAddress}";\n` +
        `export const fxrpOftAdapterAddress = "${OFT_ADAPTER_ADDRESS}";\n` +
        `export const fxrpLzBridgeShimDstEid = ${DST_EID};\n` +
        `export const fxrpLzBridgeShimExecutorGas = ${EXECUTOR_GAS};\n` +
        `export const fxrpLzBridgeShimAddress = "${shim.address}";\n`;

    const outPath = path.join(__dirname, "layerZeroDeploys.ts");
    fs.writeFileSync(outPath, deployFileContent);
    console.log("\nAddresses written to", outPath);
}

void deployAndVerify()
    .then(() => process.exit(0))
    .catch((err) => {
        console.error(err);
        process.exit(1);
    });
