// Generated by scripts/layerZero/deployFxrpLzBridgeShim.ts
export const fxrpAddress = "0x0b6A3645c240605887a5532109323A3E12273dc7";
export const fxrpOftAdapterAddress = "0xCd3d2127935Ae82Af54Fc31cCD9D3440dbF46639";
export const fxrpLzBridgeShimDstEid = 40161;
export const fxrpLzBridgeShimExecutorGas = 200000;
export const fxrpLzBridgeShimAddress = "0xF1b8Ba7f5cD5BB3039548BC6Cff639459b90299a";
