// Auto-generated by reserveCollateral.ts — do not edit manually
export const collateralReservationId = 0;
export const paymentAddress = "";
export const paymentReference = "";
export const amountXRP = "";
export const xrpTransactionHash = "";
export const fdcRoundId = 0;
